FROM ubuntu:19.10

RUN \
 sed -i 's/# \(.*multiverse$\)/\1/g' /etc/apt/sources.list && \
 apt-get update && \
 apt-get -y upgrade && \
 apt-get install -y build-essential && \
 apt-get install -y software-properties-common && \
#apt-get install -y ip-utils-ping && \
 apt-get install -y byobu curl git htop man unzip vim wget apache2-utils && \
 rm -rf /var/lib/apt/lists/*

# Add files.
# ADD .bashrc /root/.bashrc
# ADD .gitconfig /root/.gitconfig
# ADD .scripts /root/.scripts

# Set environment variables.
ENV HOME /root

# Define working directory.
WORKDIR /root

# Define default command.
CMD ["bash"]